<a href="https://colab.research.google.com/github/Minecka2023/npm_Minetska_3-14/blob/main/LB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Перше завдання
import numpy as np
A = np.matrix([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
B = np.matrix([[7, 5, 3], [0, 7, 5], [0, 0, 7]])
AB = A.dot(B)
BA = B.dot(A)
C = AB - BA
print(C)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [28]:
# Друге завдання
import numpy as np
A = np.matrix([[-1, 0, 2], [0, 1, 0], [1, 2, -1]])
B = A.dot(A)
print(B)

[[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [12]:
# Третє завдання
import numpy as np
A = np.matrix([[3, 0, 7], [-4, 2, 3], [-1, 1, 2]])
B = np.matrix([[1], [2], [4]])
AB = A.dot(B)
print(AB)

[[31]
 [12]
 [ 9]]


In [29]:
# Четверте завдання
import numpy as np

matrix = np.array([[2, 4, 5],
                  [1, 1, 2],
                  [2, 4, 3]])

# Обчислення визначника
determinant = np.linalg.det(matrix)

print("Визначник матриці:")
print(determinant)

Визначник матриці:
4.0


In [30]:
# П'яте завдання
import numpy as np

matrix = np.array([[2, 3, 4, 1],
                  [1, 2, 3, 4],
                  [3, 4, 1, 2],
                  [4, 1, 2, 3]])

# Обчислення визначника
determinant = np.linalg.det(matrix)

print("Визначник матриці:")
print(determinant)

Визначник матриці:
-160.00000000000009


In [31]:
# Шосте завдання
import numpy as np
A = np.matrix([[1, 2, 2], [2, 1, -2], [2, -2, 1]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [32]:
# Сьоме завдання
import numpy as np
A = np.matrix([[1, -1, 3, 4], [0, -1, 2, 1], [1, 1, -1, 2], [2, 3, -5, 3]])
rank = np.linalg.matrix_rank(A)
print(rank)

3


In [33]:
# Метод Крамера
import numpy as np
import numpy as np

# Коефіцієнти перед змінними у системі рівнянь
A = np.array([[4, 1, 4],
              [1, 1, 2],
              [2, 1, 2]])

# Вектор вільних членів
B = np.array([-2, -1, 0])

# Обчислення визначника головної матриці
det_A = np.linalg.det(A)

# Ініціалізація списку для збереження розв'язків
solutions = []

# Розв'язання системи рівнянь методом Крамера
for i in range(A.shape[1]):
    Ai = A.copy()
    Ai[:, i] = B
    det_Ai = np.linalg.det(Ai)
    xi = det_Ai / det_A
    solutions.append(xi)

# Виведення результату
print("Розв'язки системи рівнянь:")
for i, sol in enumerate(solutions):
    print(f"x{i+1} = {sol:.4f}")
print('Checking the correctness of the solution\n', np.linalg.solve(a,b).round(3))

Розв'язки системи рівнянь:
x1 = 1.0000
x2 = 2.0000
x3 = -2.0000
Checking the correctness of the solution
 [[506.667]
 [566.667]
 [426.667]]


In [34]:
# Матричний метод
import numpy as np

# Матриця коефіцієнтів A
A = np.array([[4, 1, 4],
              [1, 1, 2],
              [2, 1, 2]])

# Вектор вільних членів B
B = np.array([-2, -1, 0])

A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
B = np.matrix('-4; 10; 8')
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)

A= [[ 3 -1  2]
 [ 1  4 -1]
 [ 2  3  1]]
B= [[-4]
 [10]
 [ 8]]
[[ 0.5         0.5        -0.5       ]
 [-0.21428571 -0.07142857  0.35714286]
 [-0.35714286 -0.78571429  0.92857143]]
X= [[-1.]
 [ 3.]
 [ 1.]]


In [35]:
# Частина 2 завдання 4

import numpy as np

# Задаєм розмірність матриці N (кількість рядків) і M (кількість стовпців)
N = 4
M = 3

# Створюємо прямокутну матрицю A з випадковими елементами
A = np.random.rand(N, M)

# Знаходимо суму всіх елементів матриці
total_sum = np.sum(A)

# Знаходимо суми елементів для кожного стовпця
column_sums = np.sum(A, axis=0)

# Знаходимо долю кожного стовпця відносно загальної суми
column_proportions = column_sums / total_sum

print("Матриця A:")
print(A)
print("Загальна сума елементів матриці: {:.4f}".format(total_sum))
print("Суми елементів кожного стовпця:", column_sums)
print("Долі кожного стовпця відносно загальної суми:", column_proportions)

Матриця A:
[[0.94954618 0.44561641 0.38522371]
 [0.85944583 0.30404939 0.93693181]
 [0.18060316 0.68571204 0.50131707]
 [0.63959986 0.01272302 0.94178426]]
Загальна сума елементів матриці: 6.8426
Суми елементів кожного стовпця: [2.62919503 1.44810086 2.76525684]
Долі кожного стовпця відносно загальної суми: [0.38424184 0.21163167 0.40412649]
